# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05f21b27ee97cad5f73a032595b56f412cb9952bf1af0ef1df48274af302920d1668ce11b838e39ba4ab0305288710f9a88c67e77aa3f1e762b26d4c21a9b67a

test:
  secret_key_base: d18054998ff059c8ba2aa0044b88df0ef9ec28decf11ec242f9b0976e80247020bfd1996a48f5de8507cd49905aedd217aa5ba804419713e7a54676604c477e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
